name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow when a pull request is made to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Set up Docker Buildx for building images

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: ~/.cache/docker
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Frontend Docker image
      run: |
        cd front-end-nextjs
        docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-qr-code-frontend:latest .

    - name: Build Backend Docker image
      run: |
        cd api
        docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-qr-code-backend:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Frontend Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/devops-qr-code-frontend:latest

    - name: Push Backend Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/devops-qr-code-backend:latest

